/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coneccion;

import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisg
 */
public class Persona extends javax.swing.JFrame
{

    public static PreparedStatement reg;
    public static Connection con;
    String datos[] = new String[8];
    Statement s;
    
    boolean modi=false;


    /**
     * Creates new form Persona
     */
    public Persona()
    {
        initComponents();
        setLocationRelativeTo(null);
        sexoRG.add(jrb_fem);
        sexoRG.add(jrb_masc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jCheckBox2 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        sexoRG = new javax.swing.ButtonGroup();
        nombre_lb = new javax.swing.JLabel();
        apellido_lb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre_tf = new javax.swing.JTextField();
        ape_tf = new javax.swing.JTextField();
        tel_tf = new javax.swing.JTextField();
        correo_tf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        estudio_Combo = new javax.swing.JComboBox<>();
        libros_CB = new javax.swing.JCheckBox();
        ejercicio_CB = new javax.swing.JCheckBox();
        musica_CB = new javax.swing.JCheckBox();
        peliculas_Cb = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        consultar_btn = new javax.swing.JButton();
        Buscar_btn = new javax.swing.JButton();
        jrb_masc = new javax.swing.JRadioButton();
        jrb_fem = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IdBuscar_tf = new javax.swing.JTextField();
        elimina_btn = new javax.swing.JButton();
        modificar = new javax.swing.JButton();

        jCheckBox2.setText("jCheckBox2");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre_lb.setText("nombre");

        apellido_lb.setText("apellido");

        jLabel2.setText("telefono");

        jLabel3.setText("correo");

        tel_tf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tel_tfActionPerformed(evt);
            }
        });

        correo_tf.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                correo_tfActionPerformed(evt);
            }
        });

        jButton1.setText("Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        estudio_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Primaria", "Secundaria", "Preparatoria ", "Licenciatura", "Maestria y/o Doctorado" }));
        estudio_Combo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                estudio_ComboActionPerformed(evt);
            }
        });

        libros_CB.setText("Libros");

        ejercicio_CB.setText("Ejercicio");

        musica_CB.setText("Musica");

        peliculas_Cb.setText("Peliculas");

        jLabel1.setText("Nivel de estudio");

        jLabel4.setText("Intereses");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        consultar_btn.setText("Consultar");
        consultar_btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consultar_btnActionPerformed(evt);
            }
        });

        Buscar_btn.setText("Buscar");
        Buscar_btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Buscar_btnActionPerformed(evt);
            }
        });

        jrb_masc.setText("Masculino");

        jrb_fem.setText("Femenino");

        jLabel5.setText("Sexo");

        jLabel6.setText("ID:");

        elimina_btn.setText("eliminar");
        elimina_btn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                elimina_btnActionPerformed(evt);
            }
        });

        modificar.setText("modificar");
        modificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(91, 91, 91))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(apellido_lb)
                                .addComponent(nombre_lb))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(consultar_btn)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estudio_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(correo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tel_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ape_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 44, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ejercicio_CB)
                                            .addGap(34, 34, 34)
                                            .addComponent(peliculas_Cb))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(libros_CB)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(musica_CB))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(65, 65, 65)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrb_masc)
                                        .addGap(36, 36, 36)
                                        .addComponent(jrb_fem)))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IdBuscar_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(elimina_btn)
                        .addGap(18, 18, 18)
                        .addComponent(modificar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_lb)
                            .addComponent(nombre_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrb_masc)
                            .addComponent(jrb_fem))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido_lb)
                    .addComponent(ape_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tel_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(correo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estudio_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libros_CB)
                            .addComponent(musica_CB))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ejercicio_CB)
                            .addComponent(peliculas_Cb))))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar_btn)
                    .addComponent(Buscar_btn)
                    .addComponent(jLabel6)
                    .addComponent(IdBuscar_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elimina_btn)
                    .addComponent(modificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Conexion conect = new Conexion();
        con = conect.conectar();
        String sql = "insert into datos (nombre,apellido,telefono,correo,nvl_estudio,sexo,intereses )values(?,?,?,?,?,?,?)";
        String nom = nombre_tf.getText();
        String ap = ape_tf.getText();
        String tel = tel_tf.getText();
        String correo = correo_tf.getText();
        String nvl_est= (String)estudio_Combo.getSelectedItem();
        String sex = "";
        String intereses = "";
        
        if (jrb_fem.isSelected()==true)
        {
            sex="femenino";
        }
        else
        {
            sex="masculino";
        }
        
        
        if (libros_CB.isSelected())
        {
            intereses+="libros";
        }
        if (peliculas_Cb.isSelected())
        {
            intereses+="peliculas";
        }
        if (ejercicio_CB.isSelected())
        {
            intereses+="ejercicio";
        }
        if (musica_CB.isSelected())
        {
            intereses+="musica";
        }
       
        try
        {
            PreparedStatement exp = con.prepareStatement(sql);
            exp.setString(1, nom);
            exp.setString(2, ap);
            exp.setString(3, tel);
            exp.setString(4, correo);
            exp.setString(5, nvl_est);
            exp.setString(6,sex);
            exp.setString(7,intereses);
            // actualiza los registros
            int resp = exp.executeUpdate();
            con.close();
            if (resp > 0)
            {
                JOptionPane.showMessageDialog(null, "se registro al usuario");
            } else
            {
                JOptionPane.showMessageDialog(null, "error al registrar un usuario");
            }
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "error en Persona.Jbutton1Action");
        }
        limpiarCampos();
        

    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void rellenar()
    {
        if (datos!=null)
        {
            nombre_tf.setText(datos[1]);
            ape_tf.setText(datos[2]);
            tel_tf.setText(datos[3]);
            correo_tf.setText(datos[4]);
        }
    }
    
    public void limpiarCampos()
    {
        nombre_tf.setText("");
        ape_tf.setText("");
        tel_tf.setText("");
        correo_tf.setText("");
        nombre_tf.requestFocus();
        
    }
    
    public DefaultTableModel modelo()
    {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("correo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Nivel Estudio");
        modelo.addColumn("Sexo");
        modelo.addColumn("Intereses");
        jTable1.setModel(modelo); 
        return modelo;
        
    }
    
    public void consulta(String id)
    {
        
       DefaultTableModel modelo= modelo();
       
        
        String sql = "";
        
        if (id.equals(""))
        {
            sql = "select * from datos";
        } else
        {
            sql = "select * from datos where id = '" + id + "'";
            if (modi)
            {
                modi=false;
            }
            
        }
        
        
        Statement st;
        
         conectar();
        try
        {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next())
            {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                modelo.addRow(datos);
            }
            con.close();

            
            jTable1.setModel(modelo);
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "error Persona.consulta()......");
        }
        
        
    }
    
    public void actualizar(int id) 
    {
        conectar();
        String sql ="";
        try
        {
            s=con.createStatement();
        } catch (SQLException ex)
        {
            Logger.getLogger(Persona.class.getName()).log(Level.SEVERE, null, ex);
        }        
        String sex="";
        String intereses="";
        String nvl_est= (String)estudio_Combo.getSelectedItem();

        if (jrb_fem.isSelected()==true)
        {
            sex="femenino";
        }
        else
        {
            sex="masculino";
        }
        
        
        if (libros_CB.isSelected())
        {
            intereses+="libros";
        }
        if (peliculas_Cb.isSelected())
        {
            intereses+="peliculas";
        }
        if (ejercicio_CB.isSelected())
        {
            intereses+="ejercicio";
        }
        if (musica_CB.isSelected())
        {
            intereses+="musica";
        }
        sql = "UPDATE datos set nombre='"+nombre_tf.getText()+"',"+"apellido='"+
                    ape_tf.getText()+"',correo='"+correo_tf.getText()+"',intereses='"+intereses+"',nvl_estudio='"
               + nvl_est+"',sexo='"+sex+"',telefono='"+tel_tf.getText()+"' where id= "+id+";";

        try
        {
            s.execute(sql);
            con.close();
        } catch (SQLException ex)
        {
            Logger.getLogger(Persona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void conectar()
    {
        Conexion conect = new Conexion();
        con = conect.conectar();
    }
    
     public void eliminar(int id)    
    {
        conectar();
        
        try
        {
            s=con.createStatement();
        } catch (SQLException ex)
        {
            Logger.getLogger(Persona.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            String sql= "DELETE FROM datos WHERE id="+id+";";
            s.execute(sql);
            con.close();
            JOptionPane.showMessageDialog(null, "se eliino un registro");
            DefaultTableModel modelo= modelo();
            jTable1.setModel(modelo);
            
            
        } catch (SQLException ex)
        {
            System.out.println("error al eliminar registro  un registro");
        }
        
    }

    private void correo_tfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_correo_tfActionPerformed
    {//GEN-HEADEREND:event_correo_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo_tfActionPerformed

    private void estudio_ComboActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_estudio_ComboActionPerformed
    {//GEN-HEADEREND:event_estudio_ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudio_ComboActionPerformed

    private void consultar_btnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consultar_btnActionPerformed
    {//GEN-HEADEREND:event_consultar_btnActionPerformed
        // TODO add your handling code here:
        consulta("");
        
    }//GEN-LAST:event_consultar_btnActionPerformed

    private void Buscar_btnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Buscar_btnActionPerformed
    {//GEN-HEADEREND:event_Buscar_btnActionPerformed
        // TODO add your handling code here:
        String id = IdBuscar_tf.getText();
        if (id.equals(""))
        {
            JOptionPane.showMessageDialog(null, "debe ingresar un Id a buscar....");
        }else
        {
        consulta(id);
        rellenar();
        }
    }//GEN-LAST:event_Buscar_btnActionPerformed

    private void elimina_btnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_elimina_btnActionPerformed
    {//GEN-HEADEREND:event_elimina_btnActionPerformed
        int id = Integer.parseInt(IdBuscar_tf.getText());
        // TODO add your handling code here:
        
        eliminar(id);
    }//GEN-LAST:event_elimina_btnActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modificarActionPerformed
    {//GEN-HEADEREND:event_modificarActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(IdBuscar_tf.getText());
        actualizar(id);
       
    }//GEN-LAST:event_modificarActionPerformed

    private void tel_tfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tel_tfActionPerformed
    {//GEN-HEADEREND:event_tel_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            javax.swing.UIManager.setLookAndFeel(new BernsteinLookAndFeel());
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar_btn;
    private javax.swing.JTextField IdBuscar_tf;
    private javax.swing.JTextField ape_tf;
    private javax.swing.JLabel apellido_lb;
    private javax.swing.JButton consultar_btn;
    private javax.swing.JTextField correo_tf;
    private javax.swing.JCheckBox ejercicio_CB;
    private javax.swing.JButton elimina_btn;
    private javax.swing.JComboBox<String> estudio_Combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrb_fem;
    private javax.swing.JRadioButton jrb_masc;
    private javax.swing.JCheckBox libros_CB;
    private javax.swing.JButton modificar;
    private javax.swing.JCheckBox musica_CB;
    private javax.swing.JLabel nombre_lb;
    private javax.swing.JTextField nombre_tf;
    private javax.swing.JCheckBox peliculas_Cb;
    private javax.swing.ButtonGroup sexoRG;
    private javax.swing.JTextField tel_tf;
    // End of variables declaration//GEN-END:variables
}
